version: '3.1'
services:
  stats-server:
    build: stat-service/server
    container_name: ewm-stats-server
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - DATABASE_URL=jdbc:postgresql://stats-db:5432/stats
      - DATABASE_USERNAME=oleg
      - DATABASE_PASSWORD=password

  stats-db:
    image: postgres:14-alpine
    container_name: ewm-stats-db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=stats
      - POSTGRES_USER=oleg
      - POSTGRES_PASSWORD=password

  ewm-service:
    build: ewm-service
    container_name: ewm-service
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
    environment:
      - DATABASE_URL=jdbc:postgresql://ewm-db:5432/ewm
      - DATABASE_USERNAME=oleg
      - DATABASE_PASSWORD=password
      - STAT_SERVER_URL=http://stats-server:9090

  ewm-db:
    image: postgres:14-alpine
    container_name: ewm-service-db
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_DB=ewm
      - POSTGRES_USER=oleg
      - POSTGRES_PASSWORD=password