version: '3.1'
services:
  stats-server:
    build: stat-service/server
    container_name: stat-server-container
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://localhost:5432/stats-db
      - SPRING_DATASOURCE_USERNAME=oleg
      - SPRING_DATASOURCE_PASSWORD=password

  stats-db:
    image: postgres:14-alpine
    container_name: stat-db-container
    volumes:
      - var/lib/postgresql/data/
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB = stats-db
      - POSTGRES_USER=oleg
      - POSTGRES_PASSWORD=password

  ewm-service:
    ports:
      - "8080:8080"

  ewm-db:
    image: postgres:14-alpine
